baseurl = "https://dharmitshah.com"
languageCode = "en-us"
title = "Dharmit Shah"
theme = "keepit"
copyright = "Dharmit Shah"
enableEmoji = true
disqusShortname = "dharmitshah-com"

[Author]
	name = "dharmit"

[Permalinks]
	posts = "/:year/:month/:filename/"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	dateform        = "Jan 2, 2006"
	dateformShort   = "Jan 2"
	dateformNum     = "2006-01-02"
	dateformNumTime = "2006-01-02 15:04 -0700"

	avatar = "me.jpg"
 	subtitle = "just another earthling"
	author = "Dharmit Shah"

[params.share]
Twitter = true
Facebook = true
HackerNews = true
Linkedin = true

[params.social]
	goodreads = "8656610-dharmit-shah"
	github = "dharmit"
	twitter = "dharm1t"
	linkedin = "dharmitshah"
	instagram = "dh4rmit"

[blackfriday]
   	hrefTargetBlank = true

[menu]

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 10
